# Generated by Django 6.0.1 on 2026-01-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recalllog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='recalllog',
            name='user',
        ),
        migrations.AlterField(
            model_name='recalllog',
            name='confidence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recalllog',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.problem'),
        ),
        migrations.AlterField(
            model_name='recalllog',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
