# Generated by Django 6.0.1 on 2026-01-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recalllog_notes_recalllog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recalllog',
            name='next_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recalllog',
            name='priority_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
